services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: railquill
      POSTGRES_PASSWORD: password
      POSTGRES_DB: railquill_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U railquill"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://railquill:password@db:5432/railquill_development
      - RAILS_MASTER_KEY
      - BINDING=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  bundle_cache: